all: 1 2 3 4 5 6 7 8 9 10 11 12

1: try_a_random_graph.py
	python3 try_a_random_graph.py
2: try_a_random_graph.py
	python3 try_a_random_graph.py
3: try_a_random_graph.py
	python3 try_a_random_graph.py
4: try_a_random_graph.py
	python3 try_a_random_graph.py
5: try_a_random_graph.py
	python3 try_a_random_graph.py
6: try_a_random_graph.py
	python3 try_a_random_graph.py
7: try_a_random_graph.py
	python3 try_a_random_graph.py
8: try_a_random_graph.py
	python3 try_a_random_graph.py
9: try_a_random_graph.py
	python3 try_a_random_graph.py
10: try_a_random_graph.py
	python3 try_a_random_graph.py
11: try_a_random_graph.py
	python3 try_a_random_graph.py
12: try_a_random_graph.py
	python3 try_a_random_graph.py
